Completed prep-html-syntax. -Charlie McCanna
cgmccanna/prep-0122-code-solutions pull request #3
Opened 2022-01-08 22:14 UTC by cgmccanna

![HTML-syntax](https://user-images.githubusercontent.com/74582871/148661716-ef5745fa-f47b-4858-be77-9340c6b9397a.png)

2022-01-09 17:19 UTC, thebearingedge requested changes

2022-01-09 17:19 UTC, thebearingedge commented on prep-html-syntax/index.html
> +  <title>HTML Syntax</title>
Be sure to put your `<title>` in a `<head>` element.

2022-01-11 06:38 UTC, cgmccanna commented
![prep-html-syntax-updated](https://user-images.githubusercontent.com/74582871/148893517-4f175f5b-78de-4382-bfb5-687944285edd.png)

2022-01-11 15:59 UTC, thebearingedge approved these changes

2022-01-13 21:37 UTC, merged